### ISSUE TITLE
Your portfolio is awesome J

### ISSUE THREAD

**Issue by Sandile-Dev01** [qmffkem/personal_website#1]
I love the simplicity behind your portfolio bud, great job.

Here are some bugs/issues I came across while navigating it:

- The resume button background doesn’t contrast well will the button it is on.
- The resume button doesn’t direct me to your resume it changes nothing.

NB : I’m viewing your project using a mobile phone (OS)

**Comment by JaeungJayJang** [comment]
Hello Sandile!
thank you for your sincere comments and thank you for visiting my website :)

I will play with the resume button more to make it  stand out and oh my god... I did not realize i didn't link my resume there 😂
I will link my resume as well. Thank you again for your comments and have a good day! 👍

**Comment by Sandile-Dev01** [comment]
You’re welcome bro, keep safe😊
